- name: Create Per-App AS3 configurations
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create AS3 JSON
      ansible.builtin.template:
        src: templates/http.j2
        dest: temp_as3

    - name: Pretty Print AS3
      shell: jq . temp_as3 > as3/{{name}}.json

    - name: Create TF config file
      ansible.builtin.template:
        src: templates/tf.j2
        dest: tf/{{name
